### ISSUE TITLE
Light turns off after some seconds

### ISSUE THREAD

**Issue by fedejsoren** [mccarthyryanc/busylight#2]
Hi!

I started using your library and it works pretty good. I am happy I can even develop on top of that some scripts for controlling the light the way I want. The only thing that I noticed is that after some seconds, if I "just" tell the busylight to show red, it turns off after some seconds.

Do you have a way to keep the light on until I decide to clear it? 

Thank you!

PS: I couldn't find a way to contact you, so... I decided to open an issue, I hope it is ok for you :)

**Comment by mccarthyryanc** [comment]
@fedejsoren opening an issue works and happy accept any pull requests with useful updates!

As for the timer, sounds like a good feature request. I mostly followed the [spec sheet](https://github.com/porsager/busylight/files/273865/Busylight.API.rev.2.2.-.22052015.pdf) from this [javascript repo](https://github.com/porsager/busylight). There are on/off timer values, but they only go up to 25.5 sec. The js-busylight repo has a [keepalive](https://github.com/porsager/busylight/blob/master/lib/busylight.js#L189) option that does what you want. Perhaps there is a way to replicate that behavior here.

**Comment by fedejsoren** [comment]
Cool! 

As soon as I have some minutes to play with it around I will go for building the keep alive functionality, afterwards if you want I can make a pull request with that :) (unless you are faster than me :P )

Thank you!

**Comment by mccarthyryanc** [comment]
@fedejsoren , not sure if you're still following this repo, but I've moved over to [GitLab](https://gitlab.com/ryanmcginger/busylite). Create a new issue over there if this is a feature you'd still like.
